### PR TITLE
Convert DE Desktop to new swatches

### PR DESCRIPTION
**Pull request by Abban**
I realised that if that the more banners we have when
they swap the default skin to Vector 2022 that the more
work it'll be to swap all the old ones over to it.

I did the effort work in now to swap our existing ones over
and if they do change the skin during the campaign we will
have saved ourselves some headaches.

### CODE REVIEW

**Comment by gbirke** [comment]
Thanks for doing this and basing it on my PR! Unfortunately I had to rebase mine again to fix a typo, so you'd also have to rebase this on to my new PR (maybe using the `rebase --onto` method)

**Review by gbirke — APPROVED** [review]

**Comment by Abban** [comment]
That's fine, I need to rebase main into this anyway to get the use of funds styles. We can merge your PR first then I'll grab main

**Comment by Abban** [comment]
Contains the changes from https://github.com/wmde/fundraising-banners/pull/528 so don't merge this until that one is reviewed and merged.

**Comment by Abban** [comment]
I also added some fixes for the Treedip theme into this as it was the easiest place to make them.

**Comment by gbirke** [comment]
I noticed in the discussions for https://phabricator.wikimedia.org/T374099 that the new Desktop banner had some troubles with the missing swatches. you might want to coordinate with @Sperling-0 to merge/incorporate this into #543

**Pull request merged**
