### PR TITLE
C24_WPDE_Mobile_01

### PR DESCRIPTION
**Pull request by Sperling-0**
- Both banners

    - are based on the control banner of last year's mobile-wpde-01.
    - have a second button in the mobile mini banner.
    - still use the soft close.
    - still show the "Habe schon gespendet" button in the soft close.
    - show an additional paragraph on the second form page (see below).
    - are documented by screenshots in Shutterbug.

- Control banner

    - uses €5 in the button and the headline.

- Variant banner

    - uses €15 in the button and the headline.
    
Ticket: https://phabricator.wikimedia.org/T376792

### CODE REVIEW

**Review by Abban — APPROVED** [review]

**Comment by Sperling-0** [comment]
⚠️ Rebase this PR from latest main.

To get the latest UoF working:

- For Desktop banners: `BannerCtrl.vue`, `BannerVar.vue`, `FallbackBanner.vue` needs to be updated. (If it is DE desktop include DE infographic and vice versa)
- For Mobile/ Ipad banners: `BannerCtrl.vue`, `BannerVar.vue` needs to be updated. (If it is DE mobile include DE infographic and vice versa)

**Comment by Sperling-0** [comment]
> ⚠️ Rebase this PR from latest main.
> 
> To get the latest UoF working:
> 
>     * For Desktop banners: `BannerCtrl.vue`, `BannerVar.vue`, `FallbackBanner.vue` needs to be updated. (If it is DE desktop include DE infographic and vice versa)
> 
>     * For Mobile/ Ipad banners: `BannerCtrl.vue`, `BannerVar.vue` needs to be updated. (If it is DE mobile include DE infographic and vice versa)

✅ Done

**Comment by moiikana** [comment]
>[!TIP]
> rebasing might be relevant here because  https://github.com/wmde/fundraising-banners/pull/590 got merged

**Comment by Sperling-0** [comment]
> Tip
> 
> rebasing might be relevant here because #590 got merged

✅ Done

**Comment by moiikana** [comment]
consider rebasing because https://github.com/wmde/fundraising-banners/pull/597 got merged

**Comment by Sperling-0** [comment]
> consider rebasing because #597 got merged

@moiikana Why is rebasing needed? (Asking this question, because I would like to know what should I take care of when rebasing? What will be the impact? It would be great if you know the answers and would like to do a quick knowledge share on the latest updates.)

**Comment by moiikana** [comment]
it will remove info icons here because they are not needed and are broken for banners that support darkmode already
Bildschirmfoto vom 2024-10-25 16-17-30

**Comment by Sperling-0** [comment]
> consider rebasing because #597 got merged

✅ Done

**Pull request merged**
