### PR TITLE
Add ADR for naming themes

### PR DESCRIPTION
**Pull request by gbirke**
This is for https://phabricator.wikimedia.org/T327623

### CODE REVIEW

**Comment by moiikana** [comment]
@ everyone:
I'd like to propose to have 1 name for mobile and desktop themes that share the same appearance.

e.g. "funnyWhiteOrangeTheme" (desktop) and "funnyWhiteOrangeTheme_mobile" for the mobile banner that uses the same color scheme / main elements
Talking about the design ( at least team internal ) might be easier with less new names to handle.
Please let me know what you think

**Comment by Sperling-0** [comment]
> @ everyone: I'd like to propose to have 1 name for mobile and desktop themes that share the same appearance.
> 
> e.g. `funnyWhiteOrangeTheme` (desktop) and `funnyWhiteOrangeTheme_mobile` for the mobile banner that uses the same color scheme / main elements.
> 
> Talking about the design ( at least team internal ) might be easier with less new names to handle. Please let me know what you think

I agree with @moiikana here. Also, as we have only two options for our theme names, I feel using the 'creative animal' names for our themes would be better. As we won't have to remember new words (which are dummy).

**Comment by Abban** [comment]
We just need to make sure the names we pick have as few syllables as possible, so maybe we need to audit that list before generating?

**Comment by gbirke** [comment]
Hi @wmde/funtech-core I've adapted the ADR to your suggestions (adding suffixes, using the random pronounceable word generator because it can generate short 6-character words) and added the word list. Feel free to use the comment/suggest function to strike words you can't pronounce or don't like.

**Review by Abban — APPROVED** [review]

**Pull request merged**
