### PR TITLE
C24_WMDE_Desktop_EN_04

### PR DESCRIPTION
**Pull request by Sperling-0**
- Both banners
  - are based on the control banner of desktop-en-03.
  - have their form element font size increased by 10%.
  - have a fix for the radio button label alignment.
  - are hidden if the viewport width is decreased below 800px after loading the banner (see [desktop-de-11](https://phabricator.wikimedia.org/T379246)).

- Control banner
  - The space in "1 %" is removed.

- Variant banner
  - uses different copy.

- Replace window timer with injected timer (https://github.com/wmde/fundraising-banners/pull/601)
  - Components that use timers are hard to test. This removed the window timers and replaces them with an interface that we can mock.
  - Updates all tests and banners to use the new timer.
- Remove import comments in entry points We previously tried to separate the imports in the banner entry points into
  - logical sections. This didn't work well with IDE auto adding them at the bottom each time a new object was added. It was also a little confusing as to what should go where.
  - This removes the comments and embraces js import chaos.
  
Ticket: https://phabricator.wikimedia.org/T379627

### CODE REVIEW

**Review by Abban — APPROVED** [review]
Don't forget to add the `expectClosesBannerWhenWindowBecomesSmall` test to both banners

**Comment by Abban** [comment]
Can you rebase main before putting this banner live? The banner will then have the Linux FF line height fix.

**Comment by Sperling-0** [comment]
> Don't forget to add the `expectClosesBannerWhenWindowBecomesSmall` test to both banners

Thank you. I added the tests in their respective commits.

**Comment by Sperling-0** [comment]
> Can you rebase main before putting this banner live? The banner will then have the Linux FF line height fix.

✅ Done.

**Comment by moiikana** [comment]
needs same changes as in https://github.com/wmde/fundraising-banners/pull/619 and a rebase

**Comment by moiikana** [comment]
thanks for updating the PR description

**Review by moiikana — APPROVED** [review]

**Pull request merged**
