### PR TITLE
C24_WMDE_Mobile_EN_01

### PR DESCRIPTION
**Pull request by Abban**
Based on ctrl of C23_WMDE_Mobile_EN_02

- Add styles for the upgrade to yearly form
- Add event tracking for soft close already donated
- Add clickable headline that shows Use of Funds
- Add colours for light and dark mode
- Add test

Ticket: https://phabricator.wikimedia.org/T376794

### CODE REVIEW

**Comment by Sperling-0** [comment]
⚠️ Rebase this PR from latest main.

To get the latest UoF working:

- For Desktop banners: `BannerCtrl.vue`, `BannerVar.vue`, `FallbackBanner.vue` needs to be updated. (If it is DE desktop include DE infographic and vice versa)
- For Mobile/ Ipad banners: `BannerCtrl.vue`, `BannerVar.vue` needs to be updated. (If it is DE mobile include DE infographic and vice versa)

**Review by Sperling-0 — COMMENTED** [review]
I have left some comments in the ticket.

**Comment by moiikana** [comment]
needs to be rebased because of https://github.com/wmde/fundraising-banners/pull/597

**Review by moiikana — APPROVED** [review]
probably should get a rebase on main, but looks good to be merged

**Pull request merged**
