### PR TITLE
C23_WPDE_Desktop_01

### PR DESCRIPTION
**Pull request by Abban**
VAR banner uses translated WMF copy.

Ticket: https://phabricator.wikimedia.org/T348624

### CODE REVIEW

**Review by gbirke — APPROVED** [review]
Looks good.

For a non-broken progress bar and dynamic text in the dev environment (before the start of the campaign) you might want to change some values in `src/environment/dev/CampaignParameterOverride.ts` 
- remove `startDate`
- set `updatedAt` to a date that's a few weeks in the past

We can disable the overrides once the campaign has started

**Review by gbirke — CHANGES_REQUESTED** [review]
Please rebase and add the viewport tracking calls to the event map

**Comment by Abban** [comment]
Do WPDE banners track viewport info? https://github.com/wmde/fundraising-banners-until-2022/blob/14b729382860f3f64112eed6fbb2d9fcfee8400f/shared/matomo_tracker.js#L92C5-L92C5

**Comment by gbirke** [comment]
They can't and do not, sorry for the brainfart

**Review by gbirke — APPROVED** [review]

**Pull request merged**
