### PR TITLE
Fix - Breaking single characters into a new line problem

### PR DESCRIPTION
**Pull request by Sperling-0**
- Use two different key-pair values for provisional and published headline
- Keep the old value of 'headline' for backward compatibility
- This change is as per the team agreement
- Update the related test accordingly

Ticket: https://phabricator.wikimedia.org/T352982

### CODE REVIEW

**Review by Abban — APPROVED** [review]

**Comment by Abban** [comment]
We won't be able to merge this until the Use of Funds content is updated

**Comment by gbirke** [comment]
Can be merged in Jan 2024 when no banners are online and we have new UoF metadata pages, https://meta.wikimedia.org/wiki/MediaWiki:WMDE_Fundraising/UseOfFunds_2024_EN and https://meta.wikimedia.org/wiki/MediaWiki:WMDE_Fundraising/UseOfFunds_2024_DE

**Comment by Sperling-0** [comment]
I have updated the UOF content for 2023 and 2024 DE, EN:

https://meta.wikimedia.org/wiki/MediaWiki:WMDE_Fundraising/UseOfFunds_2023_DE
https://meta.wikimedia.org/wiki/MediaWiki:WMDE_Fundraising/UseOfFunds_2023_EN

https://meta.wikimedia.org/wiki/MediaWiki:WMDE_Fundraising/UseOfFunds_2024_DE
https://meta.wikimedia.org/wiki/MediaWiki:WMDE_Fundraising/UseOfFunds_2024_EN

**Review by Abban — APPROVED** [review]

**Comment by Sperling-0** [comment]
This could be merged after content repo's _test_ branch has been merged to _production_.
We might need to update _package.lock_ to remove the remaining error.

**Comment by moiikana** [comment]
needs a content update

**Comment by Abban** [comment]
I had a kid crawling on me while I was rebasing main and made a mess of this branch.. I can see the changes are also in https://github.com/wmde/fundraising-banners/pull/352 though so I'm gonna close this one and merge that.

**Pull request closed without merging**
